spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_services
    username: root
    password: 110011
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  application:
    name: order-service
  profiles:
    active: dev

server:
  port: 8090

KAFKA_BOOSTRAPADDRESS: localhost:9192
GROUPID: order

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${APIMANAGER_SVC_SERVICE_HOST}:${APIMANAGER_SVC_PORT_8000_TCP_PORT}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
